# Generated by Django 5.1.3 on 2025-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('vida', models.IntegerField(max_length=5)),
                ('defesa', models.IntegerField(max_length=5)),
                ('força', models.IntegerField(max_length=5)),
                ('magia', models.IntegerField(max_length=5)),
                ('mana', models.IntegerField(max_length=5)),
                ('agilidade', models.IntegerField(max_length=5)),
                ('resistencia', models.IntegerField(max_length=5)),
                ('necro', models.IntegerField(max_length=5)),
                ('sorte', models.IntegerField(max_length=5)),
            ],
        ),
    ]
