# Generated by Django 5.1.3 on 2025-04-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='tipo',
            field=models.CharField(choices=[('Aliado', 'Aliado'), ('Inimigo', 'Inimigo'), ('Neutro', 'Neutro')], default='Neutro', max_length=10),
        ),
    ]
