# Generated by Django 5.2 on 2025-04-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0002_personagem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='agilidade',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='defesa',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='força',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='magia',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='mana',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='necro',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='resistencia',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='sorte',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='vida',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
