# Generated by Django 5.2 on 2025-04-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0003_alter_personagem_agilidade_alter_personagem_defesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
