# Generated by Django 5.2 on 2025-04-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0004_personagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='tipo',
            field=models.CharField(choices=[('Aliado', 'Aliado'), ('Inimigo', 'Inimigo')], default='Aliado', max_length=10),
        ),
    ]
