# Generated by Django 5.2 on 2025-04-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0005_alter_personagem_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='level',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
