# Generated by Django 5.2 on 2025-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0006_personagem_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='armadura',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
