# Generated by Django 5.2 on 2025-04-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0007_personagem_armadura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('arma', 'Arma'), ('escudo', 'Escudo'), ('poção', 'Poção'), ('outro', 'Outro')], max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('valor_efeito', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('atributo_afetado', models.CharField(choices=[('vida', 'Vida'), ('mana', 'Mana'), ('força', 'Força'), ('defesa', 'Defesa'), ('armadura', 'Armadura')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle_Control.personagem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle_Control.item')),
            ],
        ),
    ]
