# Generated by Django 5.2 on 2025-04-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0008_item_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('buff', 'Buff'), ('debuff', 'Debuff')], max_length=6)),
                ('descricao', models.TextField()),
                ('atributo_afetado', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='EfeitoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicado_em', models.DateTimeField(auto_now_add=True)),
                ('efeito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle_Control.efeito')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efeitos_ativos', to='Battle_Control.personagem')),
            ],
        ),
    ]
