# Generated by Django 5.2 on 2025-04-16 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0009_efeito_efeitoativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
