# Generated by Django 5.2 on 2025-04-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0010_alter_personagem_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efeito',
            name='atributo_afetado',
            field=models.CharField(choices=[('vida', 'Vida'), ('defesa', 'Defesa'), ('armadura', 'Armadura'), ('força', 'Força'), ('magia', 'Magia'), ('mana', 'Mana'), ('agilidade', 'Agilidade'), ('resistencia', 'Resistência'), ('necro', 'Necro'), ('sorte', 'Sorte')], max_length=20),
        ),
    ]
