# Generated by Django 5.2 on 2025-04-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0011_alter_efeito_atributo_afetado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efeito',
            name='tipo',
        ),
        migrations.AddField(
            model_name='efeito',
            name='duracao',
            field=models.IntegerField(blank=True, help_text='Duração em turnos (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='efeito',
            name='reversivel',
            field=models.BooleanField(default=True, help_text='Se marcado, o efeito será revertido ao ser removido.'),
        ),
        migrations.CreateModel(
            name='EfeitoAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('valor_aplicado', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('efeito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle_Control.efeito')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efeitos_aplicados', to='Battle_Control.personagem')),
            ],
        ),
        migrations.DeleteModel(
            name='EfeitoAtivo',
        ),
    ]
