# Generated by Django 5.2 on 2025-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0012_remove_efeito_tipo_efeito_duracao_efeito_reversivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efeito',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='efeito',
            name='duracao',
        ),
        migrations.AddField(
            model_name='efeito',
            name='tipo',
            field=models.CharField(choices=[('buff', 'Buff'), ('debuff', 'Debuff')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
