# Generated by Django 5.2 on 2025-04-16 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0013_remove_efeito_descricao_remove_efeito_duracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efeito',
            name='atributo_afetado',
        ),
        migrations.RemoveField(
            model_name='efeito',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='efeitoaplicado',
            name='valor_aplicado',
        ),
        migrations.AddField(
            model_name='efeitoaplicado',
            name='modificacoes_aplicadas',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='EfeitoModificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(choices=[('vida', 'Vida'), ('defesa', 'Defesa'), ('armadura', 'Armadura'), ('força', 'Força'), ('magia', 'Magia'), ('mana', 'Mana'), ('agilidade', 'Agilidade'), ('resistencia', 'Resistência'), ('necro', 'Necro'), ('sorte', 'Sorte')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=1, max_digits=5)),
                ('efeito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificadores', to='Battle_Control.efeito')),
            ],
        ),
    ]
