# Generated by Django 5.2 on 2025-04-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0014_remove_efeito_atributo_afetado_remove_efeito_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='dano_base',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='efeitomodificador',
            name='atributo',
            field=models.CharField(choices=[('vida', 'Vida'), ('defesa', 'Defesa'), ('armadura', 'Armadura'), ('força', 'Força'), ('magia', 'Magia'), ('mana', 'Mana'), ('agilidade', 'Agilidade'), ('resistencia', 'Resistência'), ('necro', 'Necro'), ('sorte', 'Sorte'), ('dano', 'Dano')], max_length=20),
        ),
    ]
