# Generated by Django 5.2 on 2025-04-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0015_personagem_dano_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efeitomodificador',
            name='atributo',
            field=models.CharField(choices=[('vida', 'Vida'), ('defesa', 'Defesa'), ('armadura', 'Armadura'), ('força', 'Força'), ('magia', 'Magia'), ('mana', 'Mana'), ('agilidade', 'Agilidade'), ('resistencia', 'Resistência'), ('necro', 'Necro'), ('sorte', 'Sorte'), ('bonus_dano', 'Dano')], max_length=20),
        ),
    ]
