# Generated by Django 5.2 on 2025-04-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0016_alter_efeitomodificador_atributo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='dano_base',
            new_name='dano',
        ),
        migrations.AlterField(
            model_name='efeitomodificador',
            name='atributo',
            field=models.CharField(choices=[('vida', 'Vida'), ('defesa', 'Defesa'), ('armadura', 'Armadura'), ('força', 'Força'), ('magia', 'Magia'), ('mana', 'Mana'), ('agilidade', 'Agilidade'), ('resistencia', 'Resistência'), ('necro', 'Necro'), ('sorte', 'Sorte'), ('dano', 'Dano')], max_length=20),
        ),
    ]
