# Generated by Django 5.2 on 2025-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0017_rename_dano_base_personagem_dano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='dano',
        ),
        migrations.AlterField(
            model_name='efeitomodificador',
            name='atributo',
            field=models.CharField(choices=[('vida', 'Vida'), ('defesa', 'Defesa'), ('armadura', 'Armadura'), ('força', 'Força'), ('magia', 'Magia'), ('mana', 'Mana'), ('agilidade', 'Agilidade'), ('resistencia', 'Resistência'), ('necro', 'Necro'), ('sorte', 'Sorte')], max_length=20),
        ),
    ]
