# Generated by Django 5.2 on 2025-04-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0018_remove_personagem_dano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='efeito',
            name='modificador_dano',
            field=models.IntegerField(default=0),
        ),
    ]
