# Generated by Django 5.2 on 2025-04-18 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0019_efeito_modificador_dano'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reversivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='atributo_afetado',
            field=models.CharField(choices=[('vida', 'Vida'), ('defesa', 'Defesa'), ('armadura', 'Armadura'), ('força', 'Força'), ('magia', 'Magia'), ('mana', 'Mana'), ('agilidade', 'Agilidade'), ('resistencia', 'Resistência'), ('necro', 'Necro'), ('sorte', 'Sorte')], max_length=20),
        ),
        migrations.CreateModel(
            name='ItemAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle_Control.item')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_aplicados', to='Battle_Control.personagem')),
            ],
        ),
    ]
