# Generated by Django 5.2 on 2025-04-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0020_item_reversivel_alter_item_atributo_afetado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('poção', 'Poção')], max_length=10),
        ),
    ]
