# Generated by Django 5.2 on 2025-04-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0021_alter_item_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('poção', 'Poção')], default='Poção', max_length=10),
        ),
    ]
