# Generated by Django 5.2 on 2025-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0023_personagem_barreira_magica_alter_efeito_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efeitomodificador',
            name='atributo',
            field=models.CharField(choices=[('vida', 'Vida'), ('defesa', 'Defesa'), ('armadura', 'Armadura'), ('força', 'Força'), ('magia', 'Magia'), ('mana', 'Mana'), ('agilidade', 'Agilidade'), ('resistencia', 'Resistência'), ('necro', 'Necro'), ('sorte', 'Sorte'), ('barreira_magica', 'Barreira Mágica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='atributo_afetado',
            field=models.CharField(choices=[('vida', 'Vida'), ('defesa', 'Defesa'), ('armadura', 'Armadura'), ('força', 'Força'), ('magia', 'Magia'), ('mana', 'Mana'), ('agilidade', 'Agilidade'), ('resistencia', 'Resistência'), ('necro', 'Necro'), ('sorte', 'Sorte'), ('barreira_magica', 'Barreira Mágica')], max_length=20),
        ),
    ]
