# Generated by Django 5.2 on 2025-04-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0024_alter_efeitomodificador_atributo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='passiva',
            field=models.CharField(blank=True, choices=[('bonus_barreira', 'Bônus com barreira mágica'), ('foco_acumulado', 'Dano por foco')], max_length=50, null=True),
        ),
    ]
