# Generated by Django 5.2 on 2025-04-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0025_personagem_passiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='passiva',
        ),
    ]
