# Generated by Django 5.2 on 2025-04-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0027_personagem_contador_turnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='contador_turnos',
        ),
        migrations.AddField(
            model_name='personagem',
            name='turno',
            field=models.IntegerField(default=0),
        ),
    ]
