# Generated by Django 5.2 on 2025-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0028_remove_personagem_contador_turnos_personagem_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efeito',
            name='tipo',
            field=models.CharField(choices=[('buff', 'Buff'), ('debuff', 'Debuff'), ('habilidade', 'Habilidade'), ('arma', 'Arma')], max_length=10),
        ),
    ]
