# Generated by Django 5.2 on 2025-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0029_alter_efeito_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='vida_maxima',
            field=models.IntegerField(default=100),
        ),
    ]
