# Generated by Django 5.2 on 2025-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0030_personagem_vida_maxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='vida_maxima',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
