# Generated by Django 5.2 on 2025-04-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0031_alter_personagem_vida_maxima'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze', models.PositiveIntegerField(default=0)),
                ('prata', models.PositiveIntegerField(default=0)),
                ('ouro', models.PositiveIntegerField(default=0)),
                ('platina', models.PositiveIntegerField(default=0)),
                ('personagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinheiro', to='Battle_Control.personagem')),
            ],
        ),
    ]
