# Generated by Django 5.2 on 2025-05-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Battle_Control', '0032_dinheiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinheiro',
            old_name='bronze',
            new_name='cobre',
        ),
    ]
